#!/usr/bin/env node
/**
 * scripts/generate-sitemap.js
 *
 * Generates a fresh public/sitemap.xml before every production build.
 * Run manually:        node scripts/generate-sitemap.js
 * Or add to package.json:  "prebuild": "node scripts/generate-sitemap.js"
 *
 * Usage in package.json scripts:
 *   "prebuild": "node scripts/generate-sitemap.js"
 */

const fs = require("fs");
const path = require("path");

// ── Configuration ──────────────────────────────────────────────────────────
// Use environment variable for production or fallback to development URL
const BASE_URL =
  process.env.REACT_APP_BASE_URL || "https://www.afrapayafrica.com";
const OUTPUT_PATH = path.resolve(__dirname, "../public/sitemap.xml");
const TODAY = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

/**
 * Route manifest.
 * noIndex routes are excluded automatically.
 * Add new public pages here — the script handles the rest.
 */
const ROUTES = [
  // Public marketing pages
  { path: "/", changefreq: "weekly", priority: 1.0, lastmod: TODAY },
  { path: "/pricing", changefreq: "monthly", priority: 0.9, lastmod: TODAY },
  { path: "/about", changefreq: "monthly", priority: 0.8, lastmod: TODAY },
  {
    path: "/security-info",
    changefreq: "monthly",
    priority: 0.8,
    lastmod: TODAY,
  },
  { path: "/blog", changefreq: "weekly", priority: 0.8, lastmod: TODAY },
  { path: "/contact", changefreq: "monthly", priority: 0.7, lastmod: TODAY },
  { path: "/careers", changefreq: "weekly", priority: 0.7, lastmod: TODAY },
  // Legal pages — low priority, rarely change
  {
    path: "/terms",
    changefreq: "yearly",
    priority: 0.4,
    lastmod: "2026-03-13",
  },
  {
    path: "/privacy",
    changefreq: "yearly",
    priority: 0.4,
    lastmod: "2026-03-13",
  },

  // ⚠️  DO NOT add any /auth/, /dashboard/, or other private routes below.
  //     Private routes are blocked in robots.txt via Disallow directives.
];

// ── XML builder ────────────────────────────────────────────────────────────
function buildSitemap(routes) {
  const urlEntries = routes
    .map(({ path: routePath, changefreq, priority, lastmod }) => {
      const loc = `${BASE_URL}${routePath === "/" ? "/" : routePath}`;
      return [
        "  <url>",
        `    <loc>${loc}</loc>`,
        `    <lastmod>${lastmod}</lastmod>`,
        `    <changefreq>${changefreq}</changefreq>`,
        `    <priority>${priority.toFixed(1)}</priority>`,
        "  </url>",
      ].join("\n");
    })
    .join("\n\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  AfraPay – sitemap.xml
  Auto-generated by scripts/generate-sitemap.js on ${new Date().toISOString()}
  DO NOT EDIT MANUALLY — run: node scripts/generate-sitemap.js
-->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
    http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd"
>

${urlEntries}

</urlset>
`;
}

// ── Write output ───────────────────────────────────────────────────────────
try {
  const xml = buildSitemap(ROUTES);
  fs.writeFileSync(OUTPUT_PATH, xml, "utf-8");
  console.log(`✅  Sitemap written to ${OUTPUT_PATH}`);
  console.log(`    ${ROUTES.length} URLs included`);
  console.log(`    Base URL: ${BASE_URL}`);
} catch (err) {
  console.error("❌  Failed to write sitemap:", err.message);
  process.exit(1);
}
